gpu_id: 0
use_gpu: true
seed:
- 2025
data_path: dataset/
checkpoint_dir: saved
weight_decay: 0.0
req_training: true
patience: 10
train_batch_size: 32
learner: adam
learning_rate: 0.001
learning_rate_scheduler:
- 1.0
- 50
eval_step: 1
metrics:
- MAE
- MSE
- RMSE
- MAPE
- MSPE
valid_metric: MSE
eval_batch_size: 32
inverse: false
hyper_parameters:
- seed
processes_num: 1
hyper_json_path: /root/MMTSF/NewsForecasting/src/hyper_log
