e_layers: 2
d_layers: [1,2]
factor: 3
learning_rate: [0.0005,0.0001,0.00005]
# d_model: 32
# d_ff: 32
embedding_size: 512
enc_in: 1
dec_in: 1
c_out: 1
itr: 1
use_multimodal : False
inverse : False
num_kernels: 6 #for Inception

# Additional parameters that might be useful
dropout: 0.1
n_heads: 8
activation: gelu
train_epochs: 10
use_amp: True
decomp_method: 'moving_avg'
moving_avg: 25 #window size of moving average


hyper_parameters: ["learning_rate","d_layers"]
