
embedding_size: [512]
n_heads: [2]
# n_heads: [2]
dropout: 0.1
activation: 'gelu'
factor: [3] 
# factor: [1] 
enc_in: 1
# learning_rate: [0.0001]
learning_rate: [0.0005]
use_multimodal: False
e_layers: [1]
# e_layers: [4]
d_layers: [1]
inverse: False
hyper_parameters: ["n_heads","learning_rate","embedding_size","factor","e_layers","d_layers"]
